// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

//go:build darwin && arm64 && !go1.22 && !datadog.no_waf

package lib

// THIS FILE IS AUTOGENERATED. DO NOT EDIT.

import bin "github.com/DataDog/go-libddwaf/v2/internal/lib/darwin-arm64"

var libddwaf = bin.Libddwaf

const embedNamePattern = "libddwaf-*.dylib"
